description: Unauthorized (missing/invalid token)
content:
  application/json:
    schema:
      type: object
      properties:
        status:
          type: integer
          example: 401
        message:
          type: string
          example: Unauthorized
        error:
          type: string
          example: "Token is missing or invalid"
