description: Validation error
content:
  application/json:
    schema:
      type: object
      properties:
        status:
          type: integer
          example: 422
        message:
          type: string
          example: Validation error
        details:
          type: array
          items:
            type: object
            properties:
              path:
                type: string
                example: "name"
              message:
                type: string
                example: "\"name\" is required"
