openapi: 3.1.0
info:
  version: 1.0.0
  title: Students app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of pregnant tracker app
tags:
  - name: Diaries
    description: Operations about diaries.
  - name: Auth
    description: Auth operations.
  - name: Emotion
    description: Operations about emotions.
  - name: Tasks
    description: Operations about tasks.
  - name: Users
    description: Operations about users.
  - name: Weeks
    description: Operations about weeks.
servers:
  - url: http://localhost:3000
  - url: https://project-pregnant-back.onrender.com
paths:
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
